/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 destiny.glb 
Author: Daniel Cardona (https://sketchfab.com/DanielCardonaArt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/destiny-2-character-bust-a56b08cf4d6948bdbdd1f7cd7a12d98a
Title: Destiny 2 Character Bust
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
// import src from '../assets/models/destiny2.glb'

const Destiny =(props)=> {
  const group = React.useRef()
  const { scene, animations } = useGLTF("https://res.cloudinary.com/dn07sxmaf/image/upload/v1735132282/3DPortfolio/destiny2_jdlhih.glb")
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
   const { actions } = useAnimations(animations, group);
    React.useEffect(() => {
      if (actions) {
        actions['Take 001']?.play(); // Replace 'AnimationName' with the name of your specific animation
      }
    }, [actions]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="cde323fd0e0c4aacbabae784c3d8b435fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <group name="pCylinder1" position={[0, 9, -17.831]} scale={[31.364, 28.498, 31.364]}>
                    <mesh name="pCylinder1_smokeM_0" geometry={nodes.pCylinder1_smokeM_0.geometry} material={materials.smokeM} />
                  </group>
                  <group name="polySurface4" position={[-6.223, -3.293, -0.191]}>
                    <mesh name="polySurface4_BustM_0" geometry={nodes.polySurface4_BustM_0.geometry} material={materials.BustM} />
                  </group>
                  <group name="polySurface3" position={[-7.017, -5.392, -0.191]}>
                    <mesh name="polySurface3_BustM_0" geometry={nodes.polySurface3_BustM_0.geometry} material={materials.BustM} />
                  </group>
                  <group name="polySurface2" position={[-7.665, -6.398, -0.191]}>
                    <mesh name="polySurface2_BustM_0" geometry={nodes.polySurface2_BustM_0.geometry} material={materials.BustM} />
                  </group>
                  <group name="polySurface1" position={[-6.368, -4.489, -0.191]}>
                    <mesh name="polySurface1_BustM_0" geometry={nodes.polySurface1_BustM_0.geometry} material={materials.BustM} />
                  </group>
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" />
                  <group name="bust" />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.BustM} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Destiny;

