/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 voxel_nurse.glb 
Author: pratamacam (https://sketchfab.com/pratamacam)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/voxel-nurse-d7900df98542417d8430e80f951a994d
Title: Voxel Nurse
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import src from '../assets/models/voxel_nurse.glb'

const Nurse = (props)=> {
  const { nodes, materials } = useGLTF(src)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.palette} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}
export default Nurse;


